### ISSUE TITLE
Custom tag with xml namespace

### ISSUE THREAD

**Issue by bollinger** [lihaoyi/scalatags#187]
I am attempting to use scalatags to generate html for apache wicket.

```html
<wicket:extend>
  <div wicket:id="myWicketId"> 
     <p>inside wicket block</p>
  </div>
</wicket:extend>
```

I use this code.

```scala
tag("wicket:extend")(
  div(
    attr("wicket:id"):="myWicketId",
    p("inside wicket block")
  )
)

```

Which produces an exception saying "wicket:extend" is not a valid xml tag name.
```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal tag name: wicket:extend is not a valid XML tag name
	at scalatags.text.TagFactory.tag(TagFactory.scala:14)
	at scalatags.text.TagFactory.tag$(TagFactory.scala:11)
	at scalatags.Text$all$.tag(Text.scala:31)
	at example.Main$.main(Main.scala:46)
	at example.Main.main(Main.scala)
```

Is it possible to generate wicket markup with scalatags?

**Comment by jcavat** [comment]
The easiest way is to provide your own `tag` function with your own validation : 

```
  def tag(s: String, void: Boolean = false): ConcreteHtmlTag[String] = {
    if ( !myOwnValidationTag(s) )
      throw new IllegalArgumentException(
        s"Illegal tag name: $s is not a valid XML tag name"
      )
    makeAbstractTypedTag[String](s, void, Namespace.htmlNamespaceConfig)
  }
```

**Comment by lihaoyi** [comment]
Fixed in https://github.com/lihaoyi/scalatags/commit/30b65cdf9e1abce8065f8484e54807c943d189fd
